#!/usr/bin/env node
// scripts/make-page.mjs — the fixpoint. index.html carries the SAME sentinel.mjs + fallairgap.mjs the tests and the
// mutation gate prove, inlined verbatim, and re-runs the deterministic selfCheck() in the browser. Every byte-ratio on
// the page and in llms.txt is GENERATED here by the kernel (one-kernel-rule: facts generated, never typed). CI
// regenerates and fails on any diff. CRLF is stripped so the inlined kernel is byte-identical to the module.
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const at = (f) => new URL('../' + f, import.meta.url);
const read = (f) => readFileSync(at(f), 'utf8').replace(/\r\n/g, '\n');
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

const URL_LIVE = 'https://sjgant80-hub.github.io/fall-airgap/';
const REPO = 'https://github.com/sjgant80-hub/fall-airgap';

// the measured record (sealed → run). Generated by the kernel, read here so the page matches the committed numbers.
const run = JSON.parse(read('data/run.json'));
const F = await import(pathToFileURL(at('fallairgap.mjs').pathname).href).catch(() => import('../fallairgap.mjs'));
const live = F.selfCheck();
// the page's numbers MUST equal the committed run.json (fixpoint); fail loud otherwise.
for (let i = 0; i < run.rows.length; i++) {
  const a = run.rows[i], b = live.rows[i];
  if (a.ratioPayload !== b.ratioPayload || a.jsonBytes !== b.jsonBytes) {
    console.error('DRIFT: run.json != kernel for', a.event); process.exit(1);
  }
}

// browser kernel: concat sentinel.mjs + fallairgap.mjs with module syntax stripped, so `new Function` can run it.
const stripModule = (src) => src
  .replace(/^export\s+default\s+[^;]*;\s*$/gm, '')  // drop `export default { ... };`
  .replace(/^export\s*\{[^}]*\};\s*$/gm, '')        // drop `export { ... };` re-export lines
  .replace(/^export\s+/gm, '');                     // then the leading `export ` keyword on declarations
const sentinelBody = stripModule(read('sentinel.mjs'));
const airgapBody = stripModule(
  read('fallairgap.mjs').replace(/^import\s.*from\s+'\.\/sentinel\.mjs';\s*$/gm, ''), // drop the import (wired below)
);
// SENTINEL runs in its own IIFE so its internal helpers (isObj, int, …) don't collide with the transport's;
// the transport then destructures exactly what its stripped import used to bring in.
const SENTINEL_API = 'pack,unpack,foldWitness,check,phantom,fingerprint,WIRE,PAYLOAD,SIG,OPCODES,RESOURCES';
const KERNEL = `const __S=(function(){\n${sentinelBody}\nreturn {${SENTINEL_API}};})();\n`
  + `const {${SENTINEL_API}}=__S;\n`
  + airgapBody;

const rows = run.rows;
const floor = run.floor;
const bestCoord = Math.max(...rows.map((r) => r.ratioPayload));
const bestDelta = Math.max(...rows.filter((r) => r.ratioDelta).map((r) => r.ratioDelta));
const worstWire = Math.min(...rows.map((r) => r.ratioWireVsJsonSigned));

const ratioTable = rows.map((r) => `<tr><td>${esc(r.event)}</td><td class="n">${r.jsonBytes}</td><td class="n">6</td><td class="n hot">${r.ratioPayload}×</td><td class="n">${r.deltaBytes ? r.ratioDelta + '×' : '—'}</td><td class="n dim">${r.ratioWireVsJsonSigned}×</td></tr>`).join('\n');
const floorRows = floor.map((f) => `<tr><td>${esc(f.what)}</td><td class="n">${f.bytes == null ? '—' : f.bytes + ' B'}</td><td class="dim">${esc(f.note)}</td></tr>`).join('\n');

const SCHEMA = {
  '@context': 'https://schema.org', '@type': 'SoftwareSourceCode', name: 'FALL-AIRGAP',
  description: 'Air-gap transport: real estate state-events as the SENTINEL 6-byte Primorial-Fold packet, signed and verified-before-parse, moved over WebRTC / NFC / acoustic FSK with no HTTP. The 42–100× compression claim, measured in real wire bytes.',
  codeRepository: REPO, url: URL_LIVE, programmingLanguage: 'JavaScript', license: 'https://opensource.org/licenses/MIT', author: { '@type': 'Person', name: 'Kar' },
  isBasedOn: { '@type': 'SoftwareSourceCode', name: 'SENTINEL', url: 'https://sjgant80-hub.github.io/sentinel/' },
};
const FAQ = {
  '@context': 'https://schema.org', '@type': 'FAQPage', mainEntity: [
    { '@type': 'Question', name: 'What is the 6-byte packet?', acceptedAnswer: { '@type': 'Answer', text: 'The SENTINEL Primorial-Fold packet: opcode, two 4-bit node indices, an 8-bit capability bitmask, a uint16 budget, and a κ-witness fold. A whole estate state-event in six bytes.' } },
    { '@type': 'Question', name: 'Is the 42–100× compression real?', acceptedAnswer: { '@type': 'Answer', text: `Measured here in real wire bytes: ${bestCoord}× for a 6-byte coordinate and ${bestDelta}× for a recurring 1-byte delta. But a signed-per-packet frame pays the 64-byte Ed25519 signature floor, so it is only ${worstWire}×. The big ratios are real only when the signature is amortised over a session.` } },
    { '@type': 'Question', name: 'What travels over the air?', acceptedAnswer: { '@type': 'Answer', text: 'A WebRTC DataChannel is measured live in two tabs. Acoustic FSK is measured in loopback. NFC and LoRa/Ham are design-only — they need a radio.' } },
  ],
};

const page = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>FALL-AIRGAP — the 6-byte air-gap transport</title>
<meta name="description" content="Real estate state-events as the SENTINEL 6-byte Primorial-Fold packet, signed and verified-before-parse, over WebRTC / acoustic FSK with no HTTP. The 42–100× claim, measured in real wire bytes.">
<link rel="canonical" href="${URL_LIVE}">
<meta property="og:title" content="FALL-AIRGAP — the 6-byte air-gap transport">
<meta property="og:description" content="The 42–100× compression claim, measured in real wire bytes. 6-byte signed packets over WebRTC and sound.">
<meta property="og:type" content="website">
<meta property="og:url" content="${URL_LIVE}">
<link rel="manifest" href="manifest.webmanifest">
<meta name="theme-color" content="#0b0e14">
<script type="application/ld+json">${JSON.stringify(SCHEMA)}</script>
<script type="application/ld+json">${JSON.stringify(FAQ)}</script>
<style>
:root{--bg:#0b0e14;--panel:#121725;--panel2:#0f1420;--ink:#e6edf6;--dim:#8b97ab;--line:#232c40;--hot:#5eead4;--acc:#7c9cff;--warn:#f5b54a;--bad:#ff6b6b;--ok:#4ade80;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}
@media(prefers-color-scheme:light){:root:not([data-theme=dark]){--bg:#f5f7fb;--panel:#fff;--panel2:#eef2f8;--ink:#121725;--dim:#5a6678;--line:#dde3ee;--hot:#0d9488;--acc:#3454d1}}
:root[data-theme=dark]{--bg:#0b0e14;--panel:#121725;--panel2:#0f1420;--ink:#e6edf6;--dim:#8b97ab;--line:#232c40;--hot:#5eead4;--acc:#7c9cff}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 system-ui,-apple-system,Segoe UI,Roboto,sans-serif;-webkit-text-size-adjust:100%}
.wrap{max-width:900px;margin:0 auto;padding:0 16px 80px}
header{padding:48px 0 24px;border-bottom:1px solid var(--line)}
h1{font-size:clamp(28px,6vw,46px);margin:0 0 8px;letter-spacing:-.02em}
h2{font-size:clamp(20px,4vw,26px);margin:40px 0 12px;letter-spacing:-.01em}
h3{font-size:17px;margin:22px 0 8px}
.tag{display:inline-block;font:600 12px var(--mono);color:var(--hot);border:1px solid var(--line);border-radius:999px;padding:3px 10px;margin-bottom:14px}
.lede{color:var(--dim);font-size:18px;max-width:62ch}
.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:18px 18px;margin:16px 0}
.card.flat{background:var(--panel2)}
table{width:100%;border-collapse:collapse;font-size:14px;margin:8px 0}
th,td{text-align:left;padding:8px 10px;border-bottom:1px solid var(--line)}
th{color:var(--dim);font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.04em}
td.n{font:600 14px var(--mono);text-align:right}
.hot{color:var(--hot)}.dim{color:var(--dim)}
code,.mono{font-family:var(--mono);font-size:13px}
.byte{display:inline-flex;gap:4px;flex-wrap:wrap;font-family:var(--mono)}
.byte span{background:var(--panel2);border:1px solid var(--line);border-radius:6px;padding:4px 8px;font-size:13px;min-width:34px;text-align:center}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}
@media(max-width:640px){.grid{grid-template-columns:1fr}}
button{font:600 14px system-ui;color:#06121a;background:var(--hot);border:0;border-radius:9px;padding:10px 16px;cursor:pointer}
button.ghost{background:transparent;color:var(--ink);border:1px solid var(--line)}
button:disabled{opacity:.5;cursor:not-allowed}
.log{font:12px/1.5 var(--mono);background:var(--panel2);border:1px solid var(--line);border-radius:9px;padding:10px;max-height:200px;overflow:auto;white-space:pre-wrap;word-break:break-all}
.pill{font:600 11px var(--mono);padding:2px 8px;border-radius:999px;border:1px solid var(--line)}
.pill.ok{color:var(--ok);border-color:var(--ok)}.pill.bad{color:var(--bad);border-color:var(--bad)}.pill.warn{color:var(--warn);border-color:var(--warn)}
.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin:10px 0}
a{color:var(--acc)}
.foot{color:var(--dim);font-size:13px;margin-top:40px;border-top:1px solid var(--line);padding-top:20px}
.kv{display:flex;justify-content:space-between;gap:12px;font-size:14px;padding:4px 0;border-bottom:1px dashed var(--line)}
.measured{color:var(--ok)}.design{color:var(--warn)}
</style>
</head>
<body>
<div class="wrap">
<header>
<span class="tag">AIR-GAP TRANSPORT · step ② of 4</span>
<h1>The 6-byte packet, over the Air</h1>
<p class="lede">An estate state-event is six bytes. Signed, verified before it is ever parsed, and pushed over a bidirectional channel with no HTTP. Here it is, measured in real wire bytes — and honest about the one thing that does not compress.</p>
<div class="row">
<span class="pill ok" id="hdr-coord">coordinate ${bestCoord}×</span>
<span class="pill ok" id="hdr-delta">delta ${bestDelta}×</span>
<span class="pill warn" id="hdr-wire">signed-per-packet ${worstWire}×</span>
</div>
</header>

<h2>The six bytes</h2>
<div class="card">
<div class="byte" style="margin-bottom:10px">
<span title="opcode">op</span><span title="source·target">s·t</span><span title="resources">res</span><span title="budget lo">b₀</span><span title="budget hi">b₁</span><span title="κ-witness fold">κ</span>
</div>
<p style="margin:0;color:var(--dim);font-size:14px">Byte 0 opcode · byte 1 two 4-bit node indices · byte 2 an 8-bit capability bitmask · bytes 3–4 a uint16 budget (little-endian) · byte 5 the primorial-fold κ-witness. On the wire it travels signed: <code>[sourceId:1][payload:6][signature:64] = 71 bytes</code>. The codec and the signature-first gate are <a href="https://sjgant80-hub.github.io/sentinel/">SENTINEL</a>'s live, mutation-gated kernel — reused here, not re-invented.</p>
</div>

<h2>Measured: the byte-ratio per event type</h2>
<p class="lede" style="font-size:16px">Real UTF-8 bytes, counted on the wire by the kernel below. This is the number the 15× test never measured.</p>
<div class="card">
<table>
<thead><tr><th>event</th><th>JSON</th><th>bytes</th><th>coordinate</th><th>1-byte delta</th><th>signed/packet</th></tr></thead>
<tbody id="ratio-body">
${ratioTable}
</tbody>
</table>
<p style="margin:6px 0 0;color:var(--dim);font-size:13px"><b>Read it honestly:</b> the 6-byte coordinate beats self-describing JSON <b>${rows[0].ratioPayload}–${bestCoord}×</b>, and a recurring deterministic step sent as a 1-byte delta hits <b>${bestDelta}×</b> — the receiver recomputes the step locally. But sign <em>every</em> packet and the 64-byte Ed25519 signature dominates: just <b>${worstWire}×</b> apples-to-apples. The 42–100× is real <b>only when one handshake signature authenticates a whole session</b> and coordinates then stream over it.</p>
</div>

<h3>The Shannon floor — what cannot compress</h3>
<div class="card flat">
<table>
<thead><tr><th>irreducible</th><th>size</th><th></th></tr></thead>
<tbody>${floorRows}</tbody>
</table>
</div>

<div class="row"><button id="rerun">Re-run the kernel in your browser</button><span id="rerun-out" class="pill">idle</span></div>
<div class="log" id="rerun-log" aria-live="polite"></div>

<h2>Live: 6-byte packets over a WebRTC DataChannel</h2>
<p class="lede" style="font-size:16px">Two tabs, no server. One tab opens the DataChannel, the peers trade SDP over a same-origin BroadcastChannel (STUN only — no TURN, no relay), then push signed 6-byte packets. The receiver pushes the <b>signature first</b>: a forged packet is dropped before its payload is ever parsed.</p>
<div class="card">
<div class="row">
<button id="rtc-host">Open channel (host)</button>
<button id="rtc-join" class="ghost">Join (2nd tab)</button>
<span id="rtc-state" class="pill">disconnected</span>
</div>
<div class="grid">
<div>
<h3>Send a 6-byte event</h3>
<div class="row">
<button id="send-cap" class="ghost" disabled>capability_delegation</button>
<button id="send-hb" class="ghost" disabled>heartbeat</button>
</div>
<div class="row">
<button id="send-forge" class="ghost" disabled>send a FORGED packet</button>
</div>
</div>
<div>
<h3>Received</h3>
<div class="log" id="rtc-log" aria-live="polite">open the channel in this tab, then click Join in a second tab of the same page…</div>
</div>
</div>
<p style="margin:8px 0 0;color:var(--dim);font-size:13px">Open this page in two tabs. Click <b>Open channel</b> here, <b>Join</b> there. Byte counts shown are real: 6-byte payload vs the JSON the same event would be.</p>
</div>

<h2>Acoustic FSK — the 6 bytes as sound</h2>
<p class="lede" style="font-size:16px">The packet becomes an audio chirp: each byte's bits ride two tones (FSK). A second device's mic hears it and executes. Here it is measured in loopback — encoded to audio samples and demodulated back — so the codec is proven to survive the air without needing a mic.</p>
<div class="card">
<div class="row"><button id="fsk-run">Run acoustic loopback</button><span id="fsk-out" class="pill">idle</span><button id="fsk-play" class="ghost">Play the chirp (speaker)</button></div>
<div class="log" id="fsk-log" aria-live="polite"></div>
</div>

<h2>The transports — measured vs design-only</h2>
<div class="card">
<div class="kv"><span><b>WebRTC DataChannel</b> — bidirectional, no HTTP</span><span class="pill ok measured">MEASURED (live, two tabs)</span></div>
<div class="kv"><span><b>Acoustic FSK</b> — speaker → mic, offline</span><span class="pill ok measured">MEASURED (loopback)</span></div>
<div class="kv"><span><b>NFC</b> — tap, two offline devices sync in ms</span><span class="pill warn design">DESIGN (Web NFC, Android only)</span></div>
<div class="kv"><span><b>LoRa</b> — ~$15 antenna, 10-mile city link, 6B clears the ~51B cap</span><span class="pill warn design">DESIGN (needs a radio)</span></div>
<div class="kv"><span><b>AM/FM/Ham</b> — FSK broadcast to 10,000 offline nodes</span><span class="pill warn design">DESIGN (needs a radio)</span></div>
<p style="margin:10px 0 0;color:var(--dim);font-size:13px">A 6-byte packet clears LoRa's ~51-byte max-range cap effortlessly, so the design is sound — but nothing here claims a radio ran. Measured means it ran in this browser.</p>
</div>

<h2>The Human Door</h2>
<div class="card flat">
<p style="margin:0">On an incompressible edge — money, legal, irreversible — the transport will not auto-execute. KESTREL pushes a <code>HALT_SIGN</code> (0x0E) packet; the UI renders a confirm; the human signs; the signed token passes back down to resume. A capability delegation that touches the ledger or a key, or spends over the auto-ceiling, stops at the door automatically.</p>
</div>

<h2>The immune layer & the reroute trigger</h2>
<div class="card flat">
<p style="margin:0 0 10px">A novel breach broadcasts a 6-byte geometric <b>antibody</b> coordinate; every node adjusts its lattice in real time — no 50MB patch. An unauthorised intent is never returned an error (that confirms a real door was found); it is rerouted into a zero-budget phantom cell where, with no capability budget, lateral movement is mathematically impossible.</p>
<p style="margin:0"><b>Simon's open question — reroute now, or watch the maze first?</b> Answered by tiering the trigger: a <b>crypto</b> failure (forged, unknown-source, replay) <b>seals now</b> — a forger carries zero intelligence and every millisecond near real state is risk. A <b>policy</b> failure from an <b>authenticated</b> source (budget-exceeded, resource-denied, off-κ) goes to the <b>maze</b> for a few observed intents first — the key is real, so the insider's lateral-movement intent is worth fingerprinting, and it is safe to watch because the phantom's zero budget means they can pivot nowhere.</p>
</div>

<p class="foot">
Every number on this page is generated by the mutation-gated kernel <code>fallairgap.mjs</code> (built on <code>sentinel.mjs</code>), inlined below and re-run in your browser. · <a href="${REPO}">source</a> · <a href="https://sjgant80-hub.github.io/sentinel/">SENTINEL</a> · MIT for the code.<br>
The 6-byte Primorial-Fold codec is the Konomi architecture, created by <b>Thomas Frumkin</b> (used with permission); the opcode/LIGHT lineage carries from SENTINEL. Built by Kar.
</p>
</div>

<script id="kernel" type="text/plain">
${KERNEL}
</script>
<script>
// run the SAME kernel this page is built from, in the browser.
const K = new Function(document.getElementById('kernel').textContent + '\\nreturn { selfCheck, encodeEvent, decodeEvent, measure, frame, signedMessage, sigFirstDrop, canonicalJson, utf8Bytes, OP, WIRE, PAYLOAD, SIG };')();
const $ = (id) => document.getElementById(id);
const log = (el, s) => { el.textContent += (el.textContent ? '\\n' : '') + s; el.scrollTop = el.scrollHeight; };

// ── re-run the kernel ──────────────────────────────────────────────────────────────────────
$('rerun').onclick = () => {
  const out = $('rerun-out'), box = $('rerun-log'); box.textContent = '';
  const r = K.selfCheck();
  let ok = r.roundTrips === r.of;
  log(box, 'round-trips: ' + r.roundTrips + ' / ' + r.of);
  for (const row of r.rows) {
    log(box, row.event.padEnd(24) + ' json ' + String(row.jsonBytes).padStart(4) + 'B → 6B = ' + row.ratioPayload + '×' + (row.ratioDelta ? '  · delta 1B = ' + row.ratioDelta + '×' : '') + '  · signed/packet ' + row.ratioWireVsJsonSigned + '×');
  }
  log(box, 'floor: ' + r.floor.filter(f=>f.bytes).map(f=>f.what.split(' ')[0]+' '+f.bytes+'B (no compress)').join(', '));
  out.textContent = ok ? 'kernel CLEAN' : 'MISMATCH'; out.className = 'pill ' + (ok ? 'ok' : 'bad');
};

// ── Ed25519 helpers (WebCrypto) ────────────────────────────────────────────────────────────
const edOK = (() => { try { return !!(crypto.subtle); } catch { return false; } })();
async function genKeys(){ return crypto.subtle.generateKey({name:'Ed25519'}, true, ['sign','verify']); }
async function edSign(priv,msg){ return new Uint8Array(await crypto.subtle.sign({name:'Ed25519'}, priv, msg)); }
async function edVerify(pub,sig,msg){ try { return await crypto.subtle.verify({name:'Ed25519'}, pub, sig, msg); } catch { return false; } }

// ── WebRTC two-tab demo (BroadcastChannel signaling, STUN only) ──────────────────────────────
const STUN = [{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun.cloudflare.com:3478'}];
let pc=null, dc=null, myKeys=null, peerPub=null, sourceId=(Math.random()*15|0);
const sig = new BroadcastChannel('fall-airgap-signal');
const rtcState=$('rtc-state'), rtcLog=$('rtc-log');
function setState(s,cls){ rtcState.textContent=s; rtcState.className='pill '+(cls||''); }
function enableSend(on){ ['send-cap','send-hb','send-forge'].forEach(id=>$(id).disabled=!on); }

async function ensureKeys(){ if(!myKeys && edOK){ myKeys=await genKeys(); } }
async function exportPub(k){ return Array.from(new Uint8Array(await crypto.subtle.exportKey('raw',k))); }
async function importPub(arr){ return crypto.subtle.importKey('raw',new Uint8Array(arr),{name:'Ed25519'},true,['verify']); }

function wireDC(channel){
  dc=channel;
  dc.binaryType='arraybuffer';
  dc.onopen=async()=>{ setState('connected','ok'); enableSend(true); if(edOK){ sig.postMessage({t:'pub', from:sourceId, pub:await exportPub(myKeys.publicKey)}); } };
  dc.onclose=()=>{ setState('closed','warn'); enableSend(false); };
  dc.onmessage=async(ev)=>{
    const raw=new Uint8Array(ev.data);
    // SIGNATURE FIRST: verify before the payload is parsed
    const res=K.sigFirstDrop(raw, (pub,msg,s)=>false, null); // sync fallback never used; real verify below
    if(!peerPub && !edOK){ log(rtcLog,'⚠ WebCrypto Ed25519 unavailable in this browser — cannot verify'); return; }
    const sigBytes=raw.subarray(1+K.PAYLOAD), msg=raw.subarray(0,1+K.PAYLOAD);
    const good = peerPub ? await edVerify(peerPub, sigBytes, msg) : false;
    if(!good){ log(rtcLog,'✗ DROPPED before parse — signature did not map (forged/tampered). The unverified command never compiled.'); return; }
    const payload=raw.subarray(1,1+K.PAYLOAD);
    const dec=K.decodeEvent(payload);
    const json=K.canonicalJson(dec);
    log(rtcLog,'✓ verified → '+dec.type+'  ['+Array.from(payload).join(',')+']  6B vs '+K.utf8Bytes(json)+'B JSON');
  };
}

// BroadcastChannel can only clone plain objects — RTCSessionDescription / RTCIceCandidate must be flattened.
const plainSdp=(d)=>({type:d.type, sdp:d.sdp});
const plainIce=(c)=>c.toJSON ? c.toJSON() : {candidate:c.candidate, sdpMid:c.sdpMid, sdpMLineIndex:c.sdpMLineIndex};
$('rtc-host').onclick=async()=>{
  await ensureKeys(); setState('hosting…','warn');
  pc=new RTCPeerConnection({iceServers:STUN});
  pc.onicecandidate=e=>{ if(e.candidate) sig.postMessage({t:'ice',role:'host',c:plainIce(e.candidate)}); };
  wireDC(pc.createDataChannel('fall-airgap',{ordered:true}));
  const offer=await pc.createOffer(); await pc.setLocalDescription(offer);
  sig.postMessage({t:'offer',sdp:plainSdp(pc.localDescription)});
  log(rtcLog,'→ offer sent. Open a 2nd tab and click Join.');
};
$('rtc-join').onclick=async()=>{
  await ensureKeys(); setState('joining…','warn');
  pc=new RTCPeerConnection({iceServers:STUN});
  pc.onicecandidate=e=>{ if(e.candidate) sig.postMessage({t:'ice',role:'join',c:plainIce(e.candidate)}); };
  pc.ondatachannel=e=>wireDC(e.channel);
  sig.postMessage({t:'want-offer'});
};
sig.onmessage=async(ev)=>{
  const m=ev.data;
  if(m.t==='want-offer' && pc && pc.localDescription && pc.localDescription.type==='offer'){ sig.postMessage({t:'offer',sdp:plainSdp(pc.localDescription)}); }
  else if(m.t==='offer' && pc && !pc.currentRemoteDescription && (!dc)){ await pc.setRemoteDescription(m.sdp); const a=await pc.createAnswer(); await pc.setLocalDescription(a); sig.postMessage({t:'answer',sdp:plainSdp(pc.localDescription)}); }
  else if(m.t==='answer' && pc && !pc.currentRemoteDescription){ await pc.setRemoteDescription(m.sdp); }
  else if(m.t==='ice' && pc && pc.remoteDescription){ try{ await pc.addIceCandidate(m.c); }catch{} }
  else if(m.t==='pub' && m.from!==sourceId){ peerPub = edOK ? await importPub(m.pub) : null; }
};

async function pushEvent(ev, forge){
  if(!dc || dc.readyState!=='open') return;
  const payload=K.encodeEvent(ev);
  let sigBytes;
  if(forge){ sigBytes=new Uint8Array(K.SIG); crypto.getRandomValues(sigBytes); } // random = will not map
  else { sigBytes=await edSign(myKeys.privateKey, K.signedMessage(sourceId, payload)); }
  const raw=K.frame(sourceId, payload, sigBytes);
  dc.send(raw.buffer);
  const json=K.canonicalJson(ev);
  log(rtcLog,(forge?'↯ sent FORGED ':'→ sent ')+ev.type+'  6B payload vs '+K.utf8Bytes(json)+'B JSON');
}
$('send-cap').onclick=()=>pushEvent({type:'capability_delegation',source:sourceId,target:2,resources:['budget'],budget:300},false);
$('send-hb').onclick=()=>pushEvent({type:'heartbeat',node:sourceId,seq:1234,kappa:0.618},false);
$('send-forge').onclick=()=>pushEvent({type:'capability_delegation',source:sourceId,target:2,resources:['budget'],budget:300},true);

// ── acoustic FSK loopback ────────────────────────────────────────────────────────────────────
// each bit → one of two tones; OfflineAudioContext renders the chirp, a Goertzel demod reads it back.
const F0=1500, F1=2500, BAUD=200, SR=44100; // tones + baud
function fskEncode(bytes){
  const spb=Math.round(SR/BAUD), bits=[]; for(const b of bytes){ for(let i=7;i>=0;i--) bits.push((b>>i)&1); }
  const n=bits.length*spb, buf=new Float32Array(n); let ph=0;
  for(let i=0;i<bits.length;i++){ const f=bits[i]?F1:F0; for(let s=0;s<spb;s++){ ph+=2*Math.PI*f/SR; buf[i*spb+s]=Math.sin(ph)*0.5; } }
  return {buf,spb,nbits:bits.length};
}
function goertzel(buf,start,len,f){ const w=2*Math.PI*f/SR, c=2*Math.cos(w); let s0=0,s1=0,s2=0; for(let i=0;i<len;i++){ s0=buf[start+i]+c*s1-s2; s2=s1; s1=s0; } return s1*s1+s2*s2-c*s1*s2; }
function fskDecode(buf,spb,nbits){
  const bits=[]; for(let i=0;i<nbits;i++){ const st=i*spb; const e0=goertzel(buf,st,spb,F0), e1=goertzel(buf,st,spb,F1); bits.push(e1>e0?1:0); }
  const bytes=new Uint8Array(nbits/8); for(let i=0;i<bytes.length;i++){ let v=0; for(let j=0;j<8;j++) v=(v<<1)|bits[i*8+j]; bytes[i]=v; } return bytes;
}
$('fsk-run').onclick=()=>{
  const out=$('fsk-out'), box=$('fsk-log'); box.textContent='';
  const ev={type:'capability_delegation',source:1,target:2,resources:['ledger','budget'],budget:500};
  const payload=K.encodeEvent(ev);
  log(box,'packet: ['+Array.from(payload).join(',')+']');
  const {buf,spb,nbits}=fskEncode(payload);
  log(box,'chirp: '+(buf.length/SR*1000|0)+'ms of audio ('+F0+'/'+F1+'Hz, '+BAUD+' baud)');
  const back=fskDecode(buf,spb,nbits);
  const same=Array.from(payload).every((b,i)=>b===back[i]);
  log(box,'demodulated: ['+Array.from(back).join(',')+']');
  const dec=K.decodeEvent(back);
  log(box, same && dec.ok ? '✓ survived the air (loopback): '+dec.type : '✗ corrupted');
  out.textContent = same ? 'FSK CLEAN' : 'FAIL'; out.className='pill '+(same?'ok':'bad');
};
$('fsk-play').onclick=async()=>{
  try{
    const ev={type:'heartbeat',node:5,seq:1234,kappa:0.618}; const payload=K.encodeEvent(ev);
    const {buf}=fskEncode(payload);
    const ac=new (window.AudioContext||window.webkitAudioContext)();
    const ab=ac.createBuffer(1,buf.length,SR); ab.getChannelData(0).set(buf);
    const src=ac.createBufferSource(); src.buffer=ab; src.connect(ac.destination); src.start();
    log($('fsk-log'),'♪ playing the heartbeat packet as sound…');
  }catch(e){ log($('fsk-log'),'audio blocked: '+e.message); }
};
// auto-run the deterministic checks on load so the page is self-proving
$('rerun').click();
$('fsk-run').click();
</script>
</body>
</html>`;

writeFileSync(at('index.html'), page);

// llms.txt — generated from the kernel's measured numbers
const llms = `# FALL-AIRGAP
> Air-gap transport: real estate state-events as the SENTINEL 6-byte Primorial-Fold packet, signed (Ed25519) and verified-before-parse, moved over WebRTC / acoustic FSK / NFC with no HTTP. The 42-100x compression claim, MEASURED in real wire bytes.

Live: ${URL_LIVE}
Source: ${REPO}
Built on SENTINEL (https://sjgant80-hub.github.io/sentinel/). Codec: Thomas Frumkin's Konomi primorial-fold (used with permission).

## Measured byte-ratios (real UTF-8 wire bytes)
${rows.map((r) => `- ${r.event}: ${r.jsonBytes}B JSON -> 6B coordinate = ${r.ratioPayload}x${r.ratioDelta ? `; 1B delta = ${r.ratioDelta}x` : ''}; signed-per-packet 71B vs signed-JSON = ${r.ratioWireVsJsonSigned}x`).join('\n')}

## The honest limit
The big ratios are the 6-byte COORDINATE (${rows[0].ratioPayload}-${bestCoord}x) and the 1-byte DELTA (${bestDelta}x). Signing every packet pays the irreducible 64-byte Ed25519 floor, so per-packet it is only ${worstWire}x. The 42-100x is real only when one handshake signature is amortised over a session.
Irreducible (do not compress): Ed25519 signature 64B, SHA-256 hash 32B, novel human prompt.

## Transports
- WebRTC DataChannel: MEASURED (live, two tabs, STUN only)
- Acoustic FSK: MEASURED (loopback)
- NFC (Web NFC), LoRa, AM/FM/Ham: DESIGN ONLY (need a radio)
`;
writeFileSync(at('llms.txt'), llms);
console.log('index.html + llms.txt generated · coordinate ' + bestCoord + '× · delta ' + bestDelta + '× · signed/packet ' + worstWire + '×');
